/*
 * This file was automatically generated by EvoSuite
 * Mon May 04 18:34:16 GMT 2020
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ElevatorSystem.Environment;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.Random;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PL_Interface_impl_ESTest extends PL_Interface_impl_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertNotNull(pL_Interface_impl0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      List<String> list0 = PL_Interface_impl.actionHistory;
      assertNotNull(list0);
      assertTrue(list0.isEmpty());
      assertEquals(0, list0.size());
      
      String string0 = PL_Interface_impl.listToString(list0);
      assertNotNull(string0);
      assertFalse(list0.contains(string0));
      assertTrue(list0.isEmpty());
      assertEquals(0, list0.size());
      assertEquals("", string0);
      
      pL_Interface_impl0.test(7, (-1));
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      boolean boolean0 = PL_Interface_impl.executedUnimplementedAction;
      assertFalse(boolean0);
      
      Random.setNextRandom((-5));
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertNotNull(pL_Interface_impl0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      boolean boolean0 = PL_Interface_impl.getBoolean();
      assertFalse(boolean0);
      
      pL_Interface_impl0.Specification1();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.start(0, 2801);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      // Undeclared exception!
      pL_Interface_impl0.test(3, (-1));
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertNotNull(pL_Interface_impl0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      boolean boolean0 = PL_Interface_impl.getBoolean();
      assertFalse(boolean0);
      
      pL_Interface_impl0.test(8, (-1));
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertTrue(pL_Interface_impl0.isAbortedRun());
      
      boolean boolean1 = pL_Interface_impl0.isAbortedRun();
      assertFalse(boolean1 == boolean0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertTrue(pL_Interface_impl0.isAbortedRun());
      assertTrue(boolean1);
      
      pL_Interface_impl0.randomSequenceOfActions((-3529));
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertTrue(pL_Interface_impl0.isAbortedRun());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertNotNull(pL_Interface_impl0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.Specification13();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      boolean boolean0 = PL_Interface_impl.getBoolean();
      assertFalse(boolean0);
      
      pL_Interface_impl0.test(13, (-1));
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.randomSequenceOfActions((-3532));
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertNotNull(pL_Interface_impl0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.test(2, (-1));
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      boolean boolean0 = pL_Interface_impl0.isAbortedRun();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(boolean0);
      
      Environment environment0 = pL_Interface_impl0.env;
      assertNotNull(environment0);
      
      pL_Interface_impl0.env = environment0;
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.randomSequenceOfActions((-1));
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      Random.setNextRandom(40);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertNotNull(pL_Interface_impl0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      boolean boolean0 = PL_Interface_impl.getBoolean();
      assertFalse(boolean0);
      
      pL_Interface_impl0.test(12, (-1));
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      boolean boolean1 = pL_Interface_impl0.isAbortedRun();
      assertTrue(boolean1 == boolean0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(boolean1);
      
      pL_Interface_impl0.randomSequenceOfActions((-3532));
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertNotNull(pL_Interface_impl0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.test(14, (-1));
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      boolean boolean0 = pL_Interface_impl0.isAbortedRun();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(boolean0);
      
      pL_Interface_impl0.randomSequenceOfActions((-3544));
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertNotNull(pL_Interface_impl0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.test(5, (-1));
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      boolean boolean0 = pL_Interface_impl0.isAbortedRun();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(boolean0);
      
      pL_Interface_impl0.randomSequenceOfActions((-3544));
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertNotNull(pL_Interface_impl0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.test(1, (-1));
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      boolean boolean0 = pL_Interface_impl0.isAbortedRun();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(boolean0);
      
      Environment environment0 = pL_Interface_impl0.env;
      assertNotNull(environment0);
      
      pL_Interface_impl0.env = environment0;
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.randomSequenceOfActions((-3544));
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.Specification14();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      boolean boolean1 = pL_Interface_impl0.isAbortedRun();
      assertTrue(boolean1 == boolean0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(boolean1);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertNotNull(pL_Interface_impl0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.checkOnlySpecification((-873));
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.start((-873), (-873));
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.Specification14();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      boolean boolean0 = pL_Interface_impl0.isAbortedRun();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(boolean0);
      
      int int0 = 1321528396;
      pL_Interface_impl0.start((-873), 1321528396);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.Specification3();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.randomSequenceOfActions((-873));
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      String[] stringArray0 = new String[0];
      PL_Interface_impl.main(stringArray0);
      assertEquals(0, stringArray0.length);
      
      pL_Interface_impl0.checkOnlySpecification(1321528396);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.modifiedrandomSequenceOfActions((-873));
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.randomSequenceOfActions((-873));
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.start((-2270), 100);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.checkOnlySpecification((-2440));
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.randomSequenceOfActions((-873));
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      PL_Interface_impl.actionHistory = null;
      boolean boolean1 = pL_Interface_impl0.isAbortedRun();
      assertTrue(boolean1 == boolean0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(boolean1);
      
      // Undeclared exception!
      try { 
        pL_Interface_impl0.randomSequenceOfActions((-873));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("PL_Interface_impl", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertNotNull(pL_Interface_impl0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      List<String> list0 = pL_Interface_impl0.getExecutedActions();
      assertNotNull(list0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertEquals(0, list0.size());
      assertTrue(list0.isEmpty());
      
      pL_Interface_impl0.Specification9();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      String string0 = PL_Interface_impl.listToString(list0);
      assertNotNull(string0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(list0.contains(string0));
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertEquals(0, list0.size());
      assertTrue(list0.isEmpty());
      assertEquals("", string0);
      
      pL_Interface_impl0.Specification2();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      int int0 = 6;
      pL_Interface_impl0.randomSequenceOfActions(6);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.randomSequenceOfActions((-193));
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.test(6, 456);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.Specification9();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.checkOnlySpecification((-193));
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      List<String> list1 = null;
      // Undeclared exception!
      try { 
        PL_Interface_impl.listToString((List<String>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("PL_Interface_impl", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertNotNull(pL_Interface_impl0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.Specification9();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      PL_Interface_impl.main((String[]) null);
      pL_Interface_impl0.Specification2();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.modifiedrandomSequenceOfActions(5);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.start((-1150), 5);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      String string0 = PL_Interface_impl.listToString(pL_Interface_impl0.actionHistory);
      assertNotNull(string0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertEquals(" StartFromTop bobCall aliceCall angelinaCall chuckCall StartFromBottom bobCall aliceCall angelinaCall StartFromTop monicaCall monicaCall bigMacCall 1TS 3TS", string0);
      
      pL_Interface_impl0.Specification1();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertNotNull(pL_Interface_impl0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.Specification9();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      PL_Interface_impl.actionHistory = pL_Interface_impl0.actionHistory;
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertTrue(PL_Interface_impl.actionHistory.isEmpty());
      assertEquals(0, PL_Interface_impl.actionHistory.size());
      
      pL_Interface_impl0.Specification9();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.test((-246), (-246));
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.Specification3();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.modifiedrandomSequenceOfActions(731);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.checkOnlySpecification((-1));
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.Specification14();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.Specification9();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertNotNull(pL_Interface_impl0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.env = null;
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.Specification2();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.start(1638, 1638);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.env = null;
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.Specification9();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      List<String> list0 = pL_Interface_impl0.getExecutedActions();
      assertNotNull(list0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(list0.isEmpty());
      assertEquals(20, list0.size());
      
      boolean boolean0 = PL_Interface_impl.getBoolean();
      assertFalse(boolean0);
      
      pL_Interface_impl0.Specification2();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.Specification13();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      // Undeclared exception!
      pL_Interface_impl0.Specification3();
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertNotNull(pL_Interface_impl0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.Specification2();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.Specification14();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.Specification9();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      List<String> list0 = pL_Interface_impl0.getExecutedActions();
      assertNotNull(list0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertEquals(0, list0.size());
      assertTrue(list0.isEmpty());
      
      String string0 = PL_Interface_impl.listToString(list0);
      assertNotNull(string0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(list0.contains(string0));
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertEquals(0, list0.size());
      assertTrue(list0.isEmpty());
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      int int0 = PL_Interface_impl.getIntegerMinMax((-1), (-3057));
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      int int0 = PL_Interface_impl.getIntegerMinMax((-1678), (-1678));
      assertEquals((-1678), int0);
      
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertNotNull(pL_Interface_impl0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.Specification2();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.modifiedrandomSequenceOfActions(1);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.checkOnlySpecification((-1678));
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.Specification13();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.test((-1678), 0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      String string0 = PL_Interface_impl.listToString(pL_Interface_impl0.actionHistory);
      assertNotNull(string0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertEquals(" StartFromTop StartFromTop", string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      PL_Interface_impl.main((String[]) null);
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertNotNull(pL_Interface_impl0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.modifiedrandomSequenceOfActions((-1172));
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      PL_Interface_impl.actionHistory = pL_Interface_impl0.actionHistory;
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertEquals(6, PL_Interface_impl.actionHistory.size());
      assertFalse(PL_Interface_impl.actionHistory.isEmpty());
      
      pL_Interface_impl0.Specification9();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      boolean boolean0 = pL_Interface_impl0.isAbortedRun();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(boolean0);
      
      pL_Interface_impl0.Specification14();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.test((-1172), (-2907));
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertNotNull(pL_Interface_impl0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.Specification13();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.Specification13();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.Specification9();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      boolean boolean0 = PL_Interface_impl.getBoolean();
      assertFalse(boolean0);
      
      pL_Interface_impl0.test(0, 0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.Specification2();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      int int0 = PL_Interface_impl.getIntegerMinMax(0, 0);
      assertEquals(0, int0);
      
      PL_Interface_impl.actionHistory = pL_Interface_impl0.actionHistory;
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.actionHistory.isEmpty());
      assertEquals(1, PL_Interface_impl.actionHistory.size());
      
      pL_Interface_impl0.checkOnlySpecification(364);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.Specification13();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.Specification2();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertNotNull(pL_Interface_impl0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.start(0, 0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.Specification13();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.checkOnlySpecification(0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      PL_Interface_impl.executedUnimplementedAction = true;
      pL_Interface_impl0.modifiedrandomSequenceOfActions(5);
      assertTrue(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertNotNull(pL_Interface_impl0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.test(0, 0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      PL_Interface_impl.actionHistory = pL_Interface_impl0.actionHistory;
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.actionHistory.isEmpty());
      assertEquals(1, PL_Interface_impl.actionHistory.size());
      
      boolean boolean0 = PL_Interface_impl.getBoolean();
      assertFalse(boolean0);
      
      pL_Interface_impl0.checkOnlySpecification((-710));
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.modifiedrandomSequenceOfActions((-710));
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      List<String> list0 = pL_Interface_impl0.getExecutedActions();
      assertNotNull(list0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(list0.isEmpty());
      assertEquals(2, list0.size());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      int int0 = PL_Interface_impl.getIntegerMinMax(3, 3);
      assertEquals(3, int0);
      
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertNotNull(pL_Interface_impl0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      Environment environment0 = pL_Interface_impl0.env;
      assertNull(environment0);
      
      pL_Interface_impl0.Specification2();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.Specification14();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.env = null;
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.start(3, 0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.randomSequenceOfActions(3);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      String string0 = PL_Interface_impl.listToString(pL_Interface_impl0.actionHistory);
      assertNotNull(string0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertEquals(" StartFromTop StartFromTop angelinaCall chuckCall monicaCall", string0);
      
      pL_Interface_impl0.checkOnlySpecification(1019);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertNotNull(pL_Interface_impl0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.checkOnlySpecification(0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.Specification1();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.start(0, 0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.Specification1();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      PL_Interface_impl.actionHistory = pL_Interface_impl0.actionHistory;
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(PL_Interface_impl.actionHistory.isEmpty());
      assertEquals(1, PL_Interface_impl.actionHistory.size());
      
      pL_Interface_impl0.randomSequenceOfActions(6);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.Specification9();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertNotNull(pL_Interface_impl0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      String[] stringArray0 = new String[0];
      PL_Interface_impl.main(stringArray0);
      assertEquals(0, stringArray0.length);
      
      pL_Interface_impl0.start(1868, 1868);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.Specification14();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.randomSequenceOfActions((-3));
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      String[] stringArray1 = new String[0];
      assertFalse(stringArray1.equals((Object)stringArray0));
      
      PL_Interface_impl.main(stringArray1);
      assertFalse(stringArray1.equals((Object)stringArray0));
      assertNotSame(stringArray1, stringArray0);
      assertEquals(0, stringArray1.length);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      int int0 = PL_Interface_impl.getIntegerMinMax(1, 1);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertNotNull(pL_Interface_impl0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      boolean boolean0 = pL_Interface_impl0.isAbortedRun();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertNotNull(pL_Interface_impl0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.randomSequenceOfActions((-1603));
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.Specification1();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      List<String> list0 = pL_Interface_impl0.getExecutedActions();
      assertNotNull(list0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(list0.isEmpty());
      assertEquals(1, list0.size());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertNotNull(pL_Interface_impl0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.start(0, 0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.randomSequenceOfActions((-1704));
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.Specification14();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      int int0 = PL_Interface_impl.getIntegerMinMax(3550, 3550);
      assertEquals(3550, int0);
      
      pL_Interface_impl0.Specification1();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.Specification2();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.Specification13();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      boolean boolean0 = pL_Interface_impl0.isAbortedRun();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(boolean0);
      
      pL_Interface_impl0.randomSequenceOfActions((-3546));
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.Specification2();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertNotNull(pL_Interface_impl0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      PL_Interface_impl.actionHistory = pL_Interface_impl0.actionHistory;
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertEquals(0, PL_Interface_impl.actionHistory.size());
      assertTrue(PL_Interface_impl.actionHistory.isEmpty());
      
      PL_Interface_impl.executedUnimplementedAction = false;
      String string0 = PL_Interface_impl.listToString(pL_Interface_impl0.actionHistory);
      assertNotNull(string0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertEquals("", string0);
      
      pL_Interface_impl0.Specification1();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.start(0, 0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.Specification3();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.start(0, (-1));
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertNotNull(pL_Interface_impl0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.Specification1();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.checkOnlySpecification(0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.randomSequenceOfActions((-4676));
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.randomSequenceOfActions((-4676));
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.start((-4676), 0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.Specification14();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      List<String> list0 = pL_Interface_impl0.getExecutedActions();
      assertNotNull(list0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertEquals(3, list0.size());
      assertFalse(list0.isEmpty());
      
      String string0 = PL_Interface_impl.listToString(list0);
      assertNotNull(string0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(list0.contains(string0));
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertEquals(3, list0.size());
      assertFalse(list0.isEmpty());
      assertEquals(" StartFromTop StartFromTop StartFromTop", string0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertNotNull(pL_Interface_impl0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.Specification13();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.Specification14();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertNotNull(pL_Interface_impl0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      int int0 = PL_Interface_impl.getIntegerMinMax(0, 0);
      assertEquals(0, int0);
      
      pL_Interface_impl0.Specification2();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.modifiedrandomSequenceOfActions(0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.randomSequenceOfActions(0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.Specification9();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      boolean boolean0 = PL_Interface_impl.getBoolean();
      assertFalse(boolean0);
      
      pL_Interface_impl0.Specification13();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.test(1, 1);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.Specification3();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.Specification14();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.checkOnlySpecification(0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      boolean boolean1 = PL_Interface_impl.getBoolean();
      assertFalse(boolean1 == boolean0);
      assertTrue(boolean1);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertNotNull(pL_Interface_impl0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.Specification9();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.Specification1();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Random.setNextRandom(37);
      Random.setNextRandom(37);
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertNotNull(pL_Interface_impl0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.randomSequenceOfActions(37);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.modifiedrandomSequenceOfActions(37);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertNotNull(pL_Interface_impl0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.start((-611), (-611));
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertNotNull(pL_Interface_impl0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.checkOnlySpecification((-2152));
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertNotNull(pL_Interface_impl0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      PL_Interface_impl.main((String[]) null);
      int int0 = PL_Interface_impl.getIntegerMinMax(24, 24);
      assertEquals(24, int0);
      
      pL_Interface_impl0.randomSequenceOfActions((-2370));
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertNotNull(pL_Interface_impl0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      boolean boolean0 = PL_Interface_impl.getBoolean();
      assertFalse(boolean0);
      
      pL_Interface_impl0.test(12, (-1));
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.Specification13();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      boolean boolean1 = pL_Interface_impl0.isAbortedRun();
      assertTrue(boolean1 == boolean0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(boolean1);
      
      pL_Interface_impl0.randomSequenceOfActions((-3532));
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertNotNull(pL_Interface_impl0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.Specification3();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.Specification13();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      boolean boolean0 = PL_Interface_impl.getBoolean();
      assertFalse(boolean0);
      
      pL_Interface_impl0.test(13, (-1));
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.randomSequenceOfActions((-3532));
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertNotNull(pL_Interface_impl0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      boolean boolean0 = PL_Interface_impl.getBoolean();
      assertFalse(boolean0);
      
      pL_Interface_impl0.test(3, (-1));
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      boolean boolean1 = pL_Interface_impl0.isAbortedRun();
      assertTrue(boolean1 == boolean0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertFalse(boolean1);
      
      pL_Interface_impl0.randomSequenceOfActions((-3532));
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      String string0 = PL_Interface_impl.listToString(pL_Interface_impl0.actionHistory);
      assertNotNull(string0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      assertEquals(" StartFromTop", string0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertNotNull(pL_Interface_impl0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.Specification2();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.test(2, (-1));
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.randomSequenceOfActions((-1));
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      Random.setNextRandom(40);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      assertNotNull(pL_Interface_impl0);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.modifiedrandomSequenceOfActions(697);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertFalse(pL_Interface_impl0.isAbortedRun());
      
      pL_Interface_impl0.test(8, (-1));
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertTrue(pL_Interface_impl0.isAbortedRun());
      
      boolean boolean0 = pL_Interface_impl0.isAbortedRun();
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
      assertTrue(pL_Interface_impl0.isAbortedRun());
      assertTrue(boolean0);
      
      Environment environment0 = pL_Interface_impl0.env;
      assertNotNull(environment0);
      
      pL_Interface_impl0.env = environment0;
      assertTrue(pL_Interface_impl0.isAbortedRun());
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      PL_Interface_impl.getIntegerMinMax(0, 0);
      pL_Interface_impl0.Specification3();
      pL_Interface_impl0.start(24, (-1));
      pL_Interface_impl0.modifiedrandomSequenceOfActions(24);
      pL_Interface_impl0.checkOnlySpecification((-1));
      PL_Interface_impl.listToString(pL_Interface_impl0.actionHistory);
      pL_Interface_impl0.Specification1();
      pL_Interface_impl0.isAbortedRun();
      pL_Interface_impl0.Specification13();
      pL_Interface_impl0.start(370, 24);
      PL_Interface_impl.getIntegerMinMax(0, 0);
      List<String> list0 = pL_Interface_impl0.getExecutedActions();
      PL_Interface_impl.actionHistory = list0;
      pL_Interface_impl0.isAbortedRun();
      pL_Interface_impl0.Specification14();
      pL_Interface_impl0.modifiedrandomSequenceOfActions(24);
      PL_Interface_impl.listToString(pL_Interface_impl0.actionHistory);
      pL_Interface_impl0.test(24, (-1));
      String string0 = PL_Interface_impl.listToString(pL_Interface_impl0.actionHistory);
      assertEquals(" StartFromTop angelinaCall chuckCall monicaCall bigMacCall 1TS monicaCall bigMacCall 1TS bobCall 1TS bobCall aliceCall angelinaCall bobCall aliceCall angelinaCall chuckCall bobCall StartFromTop chuckCall monicaCall monicaCall bigMacCall 1TS 3TS bobCall bobCall aliceCall angelinaCall chuckCall monicaCall monicaCall bigMacCall 1TS StartFromTop chuckCall monicaCall bigMacCall 1TS bigMacCall 1TS bobCall aliceCall 3TS", string0);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      pL_Interface_impl0.randomSequenceOfActions(0);
      pL_Interface_impl0.Specification1();
      pL_Interface_impl0.Specification3();
      pL_Interface_impl0.start(0, (-4008));
      pL_Interface_impl0.Specification13();
      pL_Interface_impl0.modifiedrandomSequenceOfActions(0);
      PL_Interface_impl.executedUnimplementedAction = false;
      pL_Interface_impl0.randomSequenceOfActions(0);
      pL_Interface_impl0.Specification9();
      pL_Interface_impl0.checkOnlySpecification(0);
      pL_Interface_impl0.Specification14();
      pL_Interface_impl0.start(3434, 3434);
      pL_Interface_impl0.start(0, 0);
      pL_Interface_impl0.Specification2();
      PL_Interface_impl.getBoolean();
      String[] stringArray0 = new String[3];
      stringArray0[0] = "R.(E!";
      stringArray0[1] = "ElevatorSystem.Floor";
      stringArray0[2] = "^QbZ+2(~";
      PL_Interface_impl.main(stringArray0);
      assertEquals(3, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      String[] stringArray0 = new String[7];
      stringArray0[3] = "aliceCall";
      stringArray0[4] = "aliceCall";
      PL_Interface_impl.main(stringArray0);
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      pL_Interface_impl0.modifiedrandomSequenceOfActions(1);
      assertFalse(pL_Interface_impl0.isAbortedRun());
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      pL_Interface_impl0.test(10, (-1));
      boolean boolean0 = PL_Interface_impl.executedUnimplementedAction;
      Random.setNextRandom((-5));
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      PL_Interface_impl.getBoolean();
      pL_Interface_impl0.test(11, (-1));
      pL_Interface_impl0.isAbortedRun();
      pL_Interface_impl0.randomSequenceOfActions((-3532));
      assertTrue(pL_Interface_impl0.isAbortedRun());
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      PL_Interface_impl pL_Interface_impl0 = new PL_Interface_impl();
      pL_Interface_impl0.Specification1();
      pL_Interface_impl0.Specification1();
      pL_Interface_impl0.randomSequenceOfActions(3);
      assertFalse(PL_Interface_impl.executedUnimplementedAction);
  }
}
