/*
 * This file was automatically generated by EvoSuite
 * Sat May 09 18:09:03 GMT 2020
 */

package ElevatorSystem;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ElevatorSystem.Elevator;
import ElevatorSystem.Environment;
import ElevatorSystem.EvilPerson;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class EvilPerson_ESTest extends EvilPerson_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      int[] intArray0 = new int[8];
      Environment environment0 = new Environment(2);
      EvilPerson evilPerson0 = new EvilPerson((String) null, 0, 0, 501, intArray0, environment0);
      Elevator elevator0 = new Elevator(environment0, false);
      elevator0.floorButtons = null;
      // Undeclared exception!
      try { 
        evilPerson0.enterElevator(elevator0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ElevatorSystem.Elevator", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      int[] intArray0 = new int[6];
      intArray0[4] = 574;
      Environment environment0 = new Environment(574);
      EvilPerson evilPerson0 = new EvilPerson("down", 435, 435, 435, intArray0, environment0);
      Elevator elevator0 = new Elevator(environment0, false);
      // Undeclared exception!
      try { 
        evilPerson0.enterElevator(elevator0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 574
         //
         verifyException("ElevatorSystem.Elevator", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      int[] intArray0 = new int[8];
      Environment environment0 = new Environment(0);
      EvilPerson evilPerson0 = null;
      try {
        evilPerson0 = new EvilPerson("6>ign", (-597), (-2881), 440, intArray0, environment0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -2881
         //
         verifyException("ElevatorSystem.Environment", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      int[] intArray0 = new int[1];
      Environment environment0 = new Environment(77);
      EvilPerson evilPerson0 = new EvilPerson("|?NoKseWK0.6I?pz", 17, 17, 17, intArray0, environment0);
      Elevator elevator0 = new Elevator(environment0, false);
      evilPerson0.enterElevator(elevator0);
      assertEquals("|?NoKseWK0.6I?pz", evilPerson0.getName());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      int[] intArray0 = new int[3];
      EvilPerson evilPerson0 = null;
      try {
        evilPerson0 = new EvilPerson("jzdf", (-1), (-1), (-1), intArray0, (Environment) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ElevatorSystem.Person", e);
      }
  }
}
