/*
 * This file was automatically generated by EvoSuite
 * Tue May 05 19:54:48 GMT 2020
 */

package ElevatorSystem;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ElevatorSystem.Elevator;
import ElevatorSystem.Environment;
import ElevatorSystem.Floor;
import ElevatorSystem.Person;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Floor_ESTest extends Floor_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Environment environment0 = new Environment(0);
      Floor floor0 = new Floor(environment0, 2);
      assertFalse(floor0.hasCall());
      
      floor0.callElevator();
      boolean boolean0 = floor0.hasCall();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Floor floor0 = new Floor((Environment) null, 0);
      int int0 = floor0.getFloorID();
      assertFalse(floor0.hasCall());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Floor floor0 = new Floor((Environment) null, (-1116));
      int int0 = floor0.getFloorID();
      assertEquals((-1116), int0);
      assertFalse(floor0.hasCall());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Environment environment0 = new Environment(1782);
      Floor floor0 = new Floor(environment0, (-132));
      Floor[] floorArray0 = new Floor[3];
      floorArray0[0] = floor0;
      environment0.floors = floorArray0;
      Person person0 = new Person("", 1782, 0, (-132), environment0);
      Elevator elevator0 = new Elevator(environment0, false, (-132), false);
      // Undeclared exception!
      try { 
        floor0.processWaitingPersons(elevator0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -132
         //
         verifyException("ElevatorSystem.Elevator", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Environment environment0 = new Environment(1);
      Floor floor0 = new Floor(environment0, 1);
      assertFalse(floor0.hasCall());
      
      Person person0 = new Person(".(iDFSOycZi@ZXW:q*", 1, 0, 0, environment0);
      floor0.addWaitingPerson(person0);
      assertTrue(floor0.hasCall());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Environment environment0 = new Environment(0);
      Floor floor0 = new Floor(environment0, 0);
      floor0.reset();
      assertFalse(floor0.hasCall());
      assertEquals(0, floor0.getFloorID());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Environment environment0 = new Environment(1);
      Floor floor0 = new Floor(environment0, 1);
      int int0 = floor0.getFloorID();
      assertFalse(floor0.hasCall());
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Environment environment0 = new Environment(0);
      Floor floor0 = new Floor(environment0, 0);
      boolean boolean0 = floor0.hasCall();
      assertFalse(boolean0);
      assertEquals(0, floor0.getFloorID());
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Floor floor0 = new Floor((Environment) null, 0);
      Environment environment0 = new Environment(0);
      Floor[] floorArray0 = new Floor[2];
      floorArray0[0] = floor0;
      environment0.floors = floorArray0;
      Person person0 = new Person("", 0, 0, 395, environment0);
      // Undeclared exception!
      try { 
        floor0.processWaitingPersons((Elevator) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ElevatorSystem.Floor", e);
      }
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      Environment environment0 = new Environment(0);
      Floor floor0 = new Floor(environment0, 0);
      Elevator elevator0 = new Elevator(environment0, true, 0, false);
      floor0.processWaitingPersons(elevator0);
      assertEquals(0, floor0.getFloorID());
      assertFalse(floor0.hasCall());
  }
}
