FAILED_TEST_COUNT = 'failed_test_count'
PASSED_TEST_COUNT = 'passed_test_count'
SUSPICIOUS = 'suspicious'
COUNT = "count"
PASSING_COUNT = "passing_count"


BUG_ID = "BUG ID"
BUGGY_STM = "BUGGY STM"
VARCOP_EXAM = "VARCOP_ENABLE_BUGGY_PC_DETECTION:EXAM"
VARCOP_DISABLE_BPC_EXAM = "VARCOP_DISABLE_BUGGY_PC_DETECTION:EXAM"
SBFL_EXAM = "SBFL:EXAM"
FB_RANK = "Arrieta et al.:RANK"
FB_EXAM = "Arrieta et al.:EXAM"
VARCOP_RANK = "VARCOP_ENABLE_BUGGY_PC_DETECTION:RANK"
VARCOP_SPACE = "VARCOP_ENABLE_BUGGY_PC_DETECTION:SPACE"
SBFL_RANK = "SBFL:RANK"
SPACE = "SPACE"
VARCOP_DISABLE_BPC_RANK = "VARCOP_DISABLE_BUGGY_PC_DETECTION:RANK"
VARCOP_SEARCH_SPACE = "WITHOUT_ISOLATION_SPACE"

AGGREGATION_ARITHMETIC_MEAN = "AGGREGATION_ARITHMETIC_MEAN"
AGGREGATION_GEOMETRIC_MEAN = "AGGREGATION_GEOMETRIC_MEAN"
AGGREGATION_MIN = "AGGREGATION_MIN"
AGGREGATION_MAX = "AGGREGATION_MAX"
AGGREGATION_MEDIAN = "AGGREGATION_MEDIAN"
AGGREGATION_MODE = "AGGREGATION_MODE"
AGGREGATION_STDEV = "AGGREGATION_STDEV"
NORMALIZATION_NONE = "DISABLE_NORMALIZATION"
NORMALIZATION_ALPHA_BETA = "ENABLE_NORMALIZATION"

STATEMENT_ID = "stm_id"
VARIANTS_FAILED = "variants_failed"
VARIANTS_PASSED = "variants_passed"

SBFL_METRIC = "SBFL_METRIC"
NUM_BUGS = "NUM_OF_BUGS"
NUM_CASES = "NUM_OF_CASES"

NUM_OF_PASSING_VARIANTS = "num_of_passing_variants"
NUM_OF_FAILING_VARIANTS = "num_of_failing_variants"

HIT = "HIT@"
HIT_VARCOP = "VARCOP"
HIT_SBFL = "SBFL"

#improvement comparison
VARCOP_VS_SBFL_IN_RANK = "VARCOP_VS_SBFL_IN_RANK"
VARCOP_VS_SBFL_IN_EXAM = "VARCOP_VS_SBFL_IN_EXAM"
VARCOP_DISABLE_BPC_VS_SBFL_IN_RANK = "VARCOP_DISABLE_BPC_VS_SBFL_IN_RANK"
VARCOP_DISABLE_BPC_VS_SBFL_IN_EXAM = "VARCOP_DISABLE_BPC_VS_SBFL_IN_EXAM"

VARCOP_WIN_RANK = "VARCOP_WIN:RANK"
VARCOP_WIN_EXAM = "VARCOP_WIN_EXAM"
VARCOP_DISABLE_BPC_WIN_RANK = "VARCOP_DISABLE_BPC_WIN_RANK"
VARCOP_DISABLE_BPC_WIN_EXAM = "VARCOP_DISABLE_BPC_WIN_EXAM"
SBFL_WIN_VARCOP_RANK = "SBFL_WIN_VARCOP_RANK"
SBFL_WIN_VARCOP_EXAM = "SBFL_WIN_VARCOP_EXAM"
SBFL_WIN_VARCOP_DISABLED_BPC_RANK = "SBFL_WIN_VARCOP_DISABLED_BPC_RANK"
SBFL_WIN_VARCOP_DISABLED_BPC_EXAM = "SBFL_WIN_VARCOP_DISABLED_BPC_EXAM"

