FAILED_TEST_COUNT = 'failed_test_count'
PASSED_TEST_COUNT = 'passed_test_count'
SUSPICIOUS = 'suspicious'
COUNT = "count"
PASSING_COUNT = "passing_count"


BUG_ID = "BUG ID"
BUGGY_STM = "BUGGY STM"
VARCOP_EXAM = "VARCOP_ENABLE_BUGGY_PC_DETECTION:EXAM"
VARCOP_DISABLE_BPC_EXAM = "VARCOP_DISABLE_BUGGY_PC_DETECTION:EXAM"
SBFL_EXAM = "SBFL:EXAM"
FB_RANK = "Arrieta et al.:RANK"
FB_EXAM = "Arrieta et al.:EXAM"
VARCOP_RANK = "VARCOP_ENABLE_BUGGY_PC_DETECTION:RANK"
VARCOP_SPACE = "VARCOP_ENABLE_BUGGY_PC_DETECTION:SPACE"
SBFL_RANK = "SBFL:RANK"
SPACE = "SPACE"
VARCOP_DISABLE_BPC_RANK = "VARCOP_DISABLE_BUGGY_PC_DETECTION:RANK"
VARCOP_SEARCH_SPACE = "WITHOUT_ISOLATION_SPACE"

AGGREGATION_ARITHMETIC_MEAN = "AGGREGATION_ARITHMETIC_MEAN"
AGGREGATION_GEOMETRIC_MEAN = "AGGREGATION_GEOMETRIC_MEAN"
AGGREGATION_MIN = "AGGREGATION_MIN"
AGGREGATION_MAX = "AGGREGATION_MAX"
AGGREGATION_MEDIAN = "AGGREGATION_MEDIAN"
AGGREGATION_MODE = "AGGREGATION_MODE"
AGGREGATION_STDEV = "AGGREGATION_STDEV"
NORMALIZATION_NONE = "NORMALIZATION_NONE"
NORMALIZATION_ALPHA_BETA = "NORMALIZATION_ALPHA_BETA"

STATEMENT_ID = "stm_id"
VARIANTS_FAILED = "variants_failed"
VARIANTS_PASSED = "variants_passed"

SBFL_METRIC = "SBFL_METRIC"
NUM_DETECTED_BUGS = "NUM_OF_DETECTED_BUGS"

