
# variants_testing_label_file = "variants_testing_label.csv"
label_for_training = "label_for_training.csv"
label_for_testing = "label_for_testing.csv"
#consistent_testing_info_file = "consistent_testing_info.csv"
#consistent_testing_normalized_info_file = "consistent_testing_info_normalized.csv"
consistent_testing_info_for_training = "consistent_testing_info_for_training.csv"
consistent_testing_normalized_info_for_training = "consistent_testing_normalized_info_for_training.csv"
consistent_testing_info_for_testing = "consistent_testing_info_for_testing.csv"
consistent_testing_normalized_info_for_testing = "consistent_testing_normalized_info_for_testing.csv"
# classified_all_cases_file = "classified_all_cases.csv"
classified_all_cases_file = "classified_all_cases_no_more_FPs.csv"
classified_testing_file = "classified_testing.csv"
#classified_testing_file = "classified_testing_no_more_FPs_FL.csv"
classified_single_bug_file = "classified_1bug.csv"
classified_by_systems_file = "classified_by_systems.csv"
classified_by_only_a_system_file = "classified_by_only_a_system_file.csv"
