/*
 * This file was automatically generated by EvoSuite
 * Sun May 24 17:24:24 GMT 2020
 */

package main;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ElevatorSystem.Elevator;
import ElevatorSystem.Environment;
import ElevatorSystem.Person;
import main.Actions;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Actions_ESTest extends Actions_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Environment environment0 = new Environment(1023);
      Actions actions0 = new Actions(environment0, (Elevator) null);
      // Undeclared exception!
      try { 
        actions0.pressInLift4();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("main.Actions", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Environment environment0 = new Environment(1689);
      Elevator elevator0 = new Elevator(environment0, false);
      Actions actions0 = new Actions(environment0, elevator0);
      actions0.e = null;
      // Undeclared exception!
      try { 
        actions0.pressInLift3();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("main.Actions", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Environment environment0 = new Environment(1873);
      Actions actions0 = new Actions(environment0, (Elevator) null);
      // Undeclared exception!
      try { 
        actions0.pressInLift2();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("main.Actions", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Environment environment0 = new Environment(385);
      Actions actions0 = new Actions(environment0, (Elevator) null);
      // Undeclared exception!
      try { 
        actions0.pressInLift1();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("main.Actions", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Environment environment0 = new Environment(1689);
      Elevator elevator0 = new Elevator(environment0, false);
      Actions actions0 = new Actions(environment0, elevator0);
      actions0.e = null;
      // Undeclared exception!
      try { 
        actions0.pressInLift0();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("main.Actions", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Environment environment0 = new Environment(2914);
      Elevator elevator0 = new Elevator(environment0, false);
      Actions actions0 = new Actions(environment0, elevator0);
      actions0.env = null;
      // Undeclared exception!
      try { 
        actions0.chuckCall();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ElevatorSystem.Person", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Environment environment0 = new Environment(100);
      Elevator elevator0 = new Elevator(environment0, false, 0, false);
      Actions actions0 = new Actions(environment0, elevator0);
      Environment environment1 = new Environment(0);
      actions0.env = environment1;
      // Undeclared exception!
      try { 
        actions0.chuckCall();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 1
         //
         verifyException("ElevatorSystem.Environment", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Environment environment0 = new Environment(1422);
      Elevator elevator0 = new Elevator(environment0, true, 1, true);
      Actions actions0 = new Actions(environment0, elevator0);
      Environment environment1 = new Environment(1);
      actions0.env = environment1;
      // Undeclared exception!
      try { 
        actions0.bobCall();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 4
         //
         verifyException("ElevatorSystem.Environment", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Environment environment0 = new Environment(55);
      Elevator elevator0 = new Elevator(environment0, true, 1362, true);
      Actions actions0 = new Actions(environment0, elevator0);
      actions0.env = null;
      // Undeclared exception!
      try { 
        actions0.angelinaCall();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ElevatorSystem.Person", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Environment environment0 = new Environment(1873);
      Elevator elevator0 = new Elevator(environment0, false);
      Actions actions0 = new Actions(environment0, elevator0);
      actions0.env = environment0;
      Environment environment1 = new Environment(3);
      actions0.env = environment1;
      // Undeclared exception!
      try { 
        actions0.aliceCall();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 3
         //
         verifyException("ElevatorSystem.Environment", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Actions actions0 = null;
      try {
        actions0 = new Actions((Environment) null, (Elevator) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("main.Actions", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Environment environment0 = new Environment(1689);
      Elevator elevator0 = new Elevator(environment0, false, 1689, false);
      Actions actions0 = new Actions(environment0, elevator0);
      Person person0 = actions0.bigMacCall();
      elevator0.enterElevator(person0);
      actions0.pressInLift0();
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Environment environment0 = new Environment(1551);
      Elevator elevator0 = new Elevator(environment0, true);
      Actions actions0 = new Actions(environment0, elevator0);
      actions0.pressInLift0();
      assertTrue(elevator0.isIdle());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Environment environment0 = new Environment(0);
      Elevator elevator0 = new Elevator(environment0, false);
      Actions actions0 = null;
      try {
        actions0 = new Actions(environment0, elevator0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // These Actions assume at least 5 Floors!
         //
         verifyException("main.Actions", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Environment environment0 = new Environment(2874);
      Elevator elevator0 = new Elevator(environment0, false, 2874, false);
      Actions actions0 = new Actions(environment0, elevator0);
      Person person0 = actions0.chuckCall();
      elevator0.enterElevator(person0);
      actions0.pressInLift4();
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Environment environment0 = new Environment(1551);
      Elevator elevator0 = new Elevator(environment0, true);
      Actions actions0 = new Actions(environment0, elevator0);
      actions0.pressInLift4();
      assertTrue(elevator0.isIdle());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Environment environment0 = new Environment(1689);
      Elevator elevator0 = new Elevator(environment0, false, 1689, false);
      Actions actions0 = new Actions(environment0, elevator0);
      Person person0 = actions0.bigMacCall();
      elevator0.enterElevator(person0);
      actions0.pressInLift3();
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Environment environment0 = new Environment(1551);
      Elevator elevator0 = new Elevator(environment0, true);
      Actions actions0 = new Actions(environment0, elevator0);
      actions0.pressInLift3();
      assertTrue(elevator0.isIdle());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Environment environment0 = new Environment(1689);
      Elevator elevator0 = new Elevator(environment0, false);
      Actions actions0 = new Actions(environment0, elevator0);
      Person person0 = actions0.bigMacCall();
      elevator0.enterElevator(person0);
      actions0.pressInLift1();
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Environment environment0 = new Environment(1689);
      Elevator elevator0 = new Elevator(environment0, false);
      Actions actions0 = new Actions(environment0, elevator0);
      actions0.pressInLift1();
      assertTrue(elevator0.isIdle());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Environment environment0 = new Environment(2874);
      Elevator elevator0 = new Elevator(environment0, false, 2874, false);
      Actions actions0 = new Actions(environment0, elevator0);
      Person person0 = actions0.chuckCall();
      elevator0.enterElevator(person0);
      actions0.pressInLift2();
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Environment environment0 = new Environment(1551);
      Elevator elevator0 = new Elevator(environment0, true);
      Actions actions0 = new Actions(environment0, elevator0);
      actions0.pressInLift2();
      assertTrue(elevator0.isIdle());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Environment environment0 = new Environment(1551);
      Elevator elevator0 = new Elevator(environment0, true);
      Actions actions0 = new Actions(environment0, elevator0);
      Person person0 = actions0.monicaCall();
      assertEquals("monica", person0.getName());
      assertEquals(1, person0.getDestination());
      assertEquals(0, person0.getOrigin());
      assertEquals(30, person0.getWeight());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Environment environment0 = new Environment(1551);
      Elevator elevator0 = new Elevator(environment0, true);
      Actions actions0 = new Actions(environment0, elevator0);
      Person person0 = actions0.aliceCall();
      assertEquals(3, person0.getOrigin());
      assertEquals("alice", person0.getName());
      assertEquals(0, person0.getDestination());
      assertEquals(40, person0.getWeight());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Environment environment0 = new Environment(1551);
      Elevator elevator0 = new Elevator(environment0, true);
      Actions actions0 = new Actions(environment0, elevator0);
      Person person0 = actions0.bobCall();
      assertTrue(elevator0.isExecutiveFloorCalling());
      assertEquals(40, person0.getWeight());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Environment environment0 = new Environment(1551);
      Elevator elevator0 = new Elevator(environment0, true);
      Actions actions0 = new Actions(environment0, elevator0);
      Person person0 = actions0.angelinaCall();
      assertEquals(40, person0.getWeight());
      assertEquals(1, person0.getDestination());
      assertEquals("angelina", person0.getName());
      assertEquals(2, person0.getOrigin());
  }
}
